#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Helpers
{
    
    #line 2 "..\..\Output\Html\Helpers\CommentTag.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Helpers\CommentTag.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    #line 4 "..\..\Output\Html\Helpers\CommentTag.cshtml"
    using DocNet.Core.Models.Comments.Xml;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class CommentTag : System.Web.WebPages.HelperPage
    {
        
        #line 7 "..\..\Output\Html\Helpers\CommentTag.cshtml"

    private static string CombineText(IEnumerable<string> text)
    {
        return String.Join("\n", text);
    }

        #line default
        #line hidden

public static System.Web.WebPages.HelperResult RenderSummary(SummaryTag summaryTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 15 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"summary-comment\">\r\n        RenderTopLevelContainer(summaryTag);\r\n" +
"    </div>\r\n");



#line 19 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderRemarks(RemarksTag remarksTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 22 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"remarks-comment\">\r\n        RenderTopLevelContainer(remarksTag);\r\n" +
"    </div>\r\n");



#line 26 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExample(ExampleTag exampleTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 29 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"example-comment\">\r\n        RenderTopLevelContainer(exampleTag);\r\n" +
"    </div>\r\n");



#line 33 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderReturns(ReturnsTag returnsTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 36 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"returns-comment\">\r\n        RenderTopLevelContainer(returnsTag);\r\n" +
"    </div>\r\n");



#line 40 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderValue(ValueTag valueTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 43 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"value-comment\">\r\n        RenderTopLevelContainer(valueTag);\r\n    " +
"</div>\r\n");



#line 47 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParam(ParameterTag paramTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 50 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"parameter-comment\">\r\n        RenderTopLevelContainer(paramTag);\r\n" +
"    </div>\r\n");



#line 54 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParam(TypeParameterTag typeParamTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 57 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"type-parameter-comment\">\r\n        RenderTopLevelContainer(typePar" +
"amTag);\r\n    </div>\r\n");



#line 61 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderException(ExceptionTag exceptionTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 64 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"exception-comment\">\r\n        RenderTopLevelContainer(exceptionTag" +
");\r\n    </div>\r\n");



#line 68 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSeeAlso(SeeAlsoTag seeAlsoTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 71 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"see-also-comment\">\r\n        <p>FixMe</p>\r\n    </div>\r\n");



#line 75 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderPermission(PermissionTag permissionTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 78 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>Fix me, I don\'t know what I am!</p>\r\n");



#line 80 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTopLevelContainer(TopLevelContainer container)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 83 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 
    foreach (var element in container.Items)
     {
         RenderContainerElement(element);
     }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderContainer(Container container)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 91 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 
    foreach (var element in container.Items)
    {
        RenderContainerElement(element);
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderContainerElement(object element)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 99 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 
    if (element is ParagraphTag)
    {
        RenderPara(element as ParagraphTag);
        return;
    }
    if (element is CTag)
    {
        RenderC(element as CTag);
        return;
    }
    if (element is CodeTag)
    {
        RenderCode(element as CodeTag);
        return;
    }
    if (element is ListTag)
    {
        RenderList();
        return;
    }
    if (element is ParameterReferenceTag)
    {
        RenderParamRef(element as ParameterReferenceTag);
        return;
    }
    if (element is SeeTag)
    {
        RenderSee(element as SeeTag);
        return;
    }
    if (element is TypeParameterReferenceTag)
    {
        RenderTypeParamRef(element as TypeParameterReferenceTag);
        return;
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderC(CTag cTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 138 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <span class=\"inline-code\">");



#line 139 "..\..\Output\Html\Helpers\CommentTag.cshtml"
WriteTo(@__razor_helper_writer, CombineText(cTag.Text));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 140 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderCode(CodeTag codeTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 143 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"code-block\">\r\n        <pre>\r\n            <code class=\"lang-csharp" +
"\">\r\n                ");



#line 147 "..\..\Output\Html\Helpers\CommentTag.cshtml"
WriteTo(@__razor_helper_writer, CombineText(codeTag.Text));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n            </code>\r\n        </pre> \r\n    </div>  \r\n");



#line 151 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderList()
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 154 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 
    

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParamRef(ParameterReferenceTag paramRefTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 159 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <b>");



#line 160 "..\..\Output\Html\Helpers\CommentTag.cshtml"
WriteTo(@__razor_helper_writer, paramRefTag.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</b>\r\n");



#line 161 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSee(SeeTag seeTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 164 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <b>");



#line 165 "..\..\Output\Html\Helpers\CommentTag.cshtml"
WriteTo(@__razor_helper_writer, seeTag.ReferencedElementName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</b>   \r\n");



#line 166 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamRef(TypeParameterReferenceTag typeParamRefTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 169 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <b>");



#line 170 "..\..\Output\Html\Helpers\CommentTag.cshtml"
WriteTo(@__razor_helper_writer, typeParamRefTag.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</b>\r\n");



#line 171 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult  RenderPara(ParagraphTag paragraphTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 174 "..\..\Output\Html\Helpers\CommentTag.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>RenderContainer(paragraphTag);</p>\r\n");



#line 176 "..\..\Output\Html\Helpers\CommentTag.cshtml"

#line default
#line hidden

});

}


        public CommentTag()
        {
        }
    }
}
#pragma warning restore 1591
