#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Helpers
{
    using System;
    
    #line 2 "..\..\Output\Html\Helpers\PageHelper.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 3 "..\..\Output\Html\Helpers\PageHelper.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    #line 4 "..\..\Output\Html\Helpers\PageHelper.cshtml"
    using DocNet.Core.Exceptions;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Helpers\PageHelper.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Helpers\PageHelper.cshtml"
    using DocNet.Core.Output.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class PageHelper : System.Web.WebPages.HelperPage
    {

public static System.Web.WebPages.HelperResult RenderHead(IEnumerable<string> includedCss, IEnumerable<string> includedScripts)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 11 "..\..\Output\Html\Helpers\PageHelper.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <head>\r\n        <meta charset=\"utf-8\">\r\n");



#line 14 "..\..\Output\Html\Helpers\PageHelper.cshtml"
         foreach (var cssFile in includedCss)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <link href=\"");



#line 16 "..\..\Output\Html\Helpers\PageHelper.cshtml"
WriteTo(@__razor_helper_writer, cssFile);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" rel=\"stylesheet\"/>\r\n");



#line 17 "..\..\Output\Html\Helpers\PageHelper.cshtml"
        }

#line default
#line hidden



#line 18 "..\..\Output\Html\Helpers\PageHelper.cshtml"
         foreach (var jsFile in includedScripts)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <script src=\"");



#line 20 "..\..\Output\Html\Helpers\PageHelper.cshtml"
WriteTo(@__razor_helper_writer, jsFile);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" type=\"text/javascript\"></script>\r\n");



#line 21 "..\..\Output\Html\Helpers\PageHelper.cshtml"
        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <script>hljs.initHighlightingOnLoad();</script>\r\n        <title>DocNet Ou" +
"tput</title>\r\n    </head>\r\n");



#line 25 "..\..\Output\Html\Helpers\PageHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSidebar(GlobalNamespaceModel globalNamespace, CsElement currentViewModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 28 "..\..\Output\Html\Helpers\PageHelper.cshtml"
 
    var sortedChilren = globalNamespace.OrderBy(child => child.DisplayName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div id=\"over\">\r\n        <h2>Hierarchy</h2>\r\n        <ul>\r\n            ");



#line 33 "..\..\Output\Html\Helpers\PageHelper.cshtml"
WriteTo(@__razor_helper_writer, RenderChildList(sortedChilren, true, currentViewModel));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n        </ul>    \r\n    </div>\r\n");



#line 36 "..\..\Output\Html\Helpers\PageHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParentElement(IParentElement parent, CsElement currentViewModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 39 "..\..\Output\Html\Helpers\PageHelper.cshtml"
 
    var sortedChildren = parent.OrderBy(child => child.DisplayName);
    bool hasChildren = sortedChildren.Any();    
    bool isExpanded = (parent == currentViewModel) || parent.HasDescendant(currentViewModel as INestableElement);

    var parentElement = parent as CsElement;
    if (parentElement == null)
    {
        throw new DocumentationGenerationException("Parent element is not a CsElement.");
    }


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <li>\r\n        <div class=\"expand link\" onclick=\"ToggleSidebarNode(this)\">\r\n");



#line 52 "..\..\Output\Html\Helpers\PageHelper.cshtml"
             if(hasChildren)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <span class=\"glyphicon ");



#line 54 "..\..\Output\Html\Helpers\PageHelper.cshtml"
         WriteTo(@__razor_helper_writer, isExpanded ? "glyphicon-menu-down" : "glyphicon-menu-right");

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"></span>\r\n");



#line 55 "..\..\Output\Html\Helpers\PageHelper.cshtml"
            }
            else
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <span class=\"expand\"></span>\r\n");



#line 59 "..\..\Output\Html\Helpers\PageHelper.cshtml"
            }            

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n        <a href=\"");



#line 61 "..\..\Output\Html\Helpers\PageHelper.cshtml"
WriteTo(@__razor_helper_writer, HtmlDocumentationGenerator.GetFileNameForCsElement(parentElement));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 61 "..\..\Output\Html\Helpers\PageHelper.cshtml"
                                                      WriteTo(@__razor_helper_writer, parentElement.DisplayName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 62 "..\..\Output\Html\Helpers\PageHelper.cshtml"
         if(hasChildren)
        {
            
#line default
#line hidden


#line 64 "..\..\Output\Html\Helpers\PageHelper.cshtml"
WriteTo(@__razor_helper_writer, RenderChildList(sortedChildren, isExpanded, currentViewModel));

#line default
#line hidden


#line 64 "..\..\Output\Html\Helpers\PageHelper.cshtml"
                                                                          
        }     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    </li>\r\n");



#line 67 "..\..\Output\Html\Helpers\PageHelper.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderChildList(IEnumerable<INestableElement> children, bool isExpanded, CsElement currentViewModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 70 "..\..\Output\Html\Helpers\PageHelper.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"child-list collapse ");



#line 71 "..\..\Output\Html\Helpers\PageHelper.cshtml"
     WriteTo(@__razor_helper_writer, isExpanded ? "in" : "");

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n\r\n");



#line 73 "..\..\Output\Html\Helpers\PageHelper.cshtml"
         foreach (var child in children)
        {
            if (child is IParentElement)
            {
                
#line default
#line hidden


#line 77 "..\..\Output\Html\Helpers\PageHelper.cshtml"
WriteTo(@__razor_helper_writer, RenderParentElement(child as IParentElement, currentViewModel));

#line default
#line hidden


#line 77 "..\..\Output\Html\Helpers\PageHelper.cshtml"
                                                                               
            }
            else
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <li><span class=\"expand\"></span><a href=\"");



#line 81 "..\..\Output\Html\Helpers\PageHelper.cshtml"
                          WriteTo(@__razor_helper_writer, HtmlDocumentationGenerator.GetFileNameForCsElement(child as CsElement));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 81 "..\..\Output\Html\Helpers\PageHelper.cshtml"
                                                                                                   WriteTo(@__razor_helper_writer, child.DisplayName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 82 "..\..\Output\Html\Helpers\PageHelper.cshtml"
            }
        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



#line 85 "..\..\Output\Html\Helpers\PageHelper.cshtml"

#line default
#line hidden

});

}


        public PageHelper()
        {
        }
    }
}
#pragma warning restore 1591
