#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Helpers
{
    
    #line 2 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 4 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    #line 5 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Core.Models.Comments;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Core.Models.Comments.Xml;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using Microsoft.CodeAnalysis;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class PageSection : System.Web.WebPages.HelperPage
    {

public static System.Web.WebPages.HelperResult RenderElementTitle(CsElement element, string elementType)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 12 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if(element is GlobalNamespaceModel)
    {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <h1>Global Namespace</h1>\r\n");



#line 16 "..\..\Output\Html\Helpers\PageSection.cshtml"
        return;
    }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <h1>");



#line 18 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, element.DisplayName + " " + elementType);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</h1>\r\n");



#line 19 "..\..\Output\Html\Helpers\PageSection.cshtml"
    if (!String.IsNullOrWhiteSpace(element.FullNameQualifier)){

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <span><b>Namespace:</b> ");



#line 20 "..\..\Output\Html\Helpers\PageSection.cshtml"
 WriteTo(@__razor_helper_writer, element.FullNameQualifier);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 21 "..\..\Output\Html\Helpers\PageSection.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderDeclarationBlock(string declaration)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 25 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    
#line default
#line hidden


#line 26 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Declaration"));

#line default
#line hidden


#line 26 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                      

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"code-block\">\r\n        <pre><code class=\"cs\">");



#line 28 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, declaration);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</code></pre>\r\n    </div>\r\n");



#line 30 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSectionTitle(string title)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 33 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <h3>");



#line 34 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</h3>\r\n");



#line 35 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSummary(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 38 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.Summary == null) { return; }
    
#line default
#line hidden


#line 40 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Summary"));

#line default
#line hidden


#line 40 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  
    
#line default
#line hidden


#line 41 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderSummary(docComment.Summary));

#line default
#line hidden


#line 41 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderRemarks(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 45 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.Remarks == null) { return; }
    
#line default
#line hidden


#line 47 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Remarks"));

#line default
#line hidden


#line 47 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  
    
#line default
#line hidden


#line 48 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderRemarks(docComment.Remarks));

#line default
#line hidden


#line 48 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExample(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 52 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.Example == null) { return; }
    
#line default
#line hidden


#line 54 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Example"));

#line default
#line hidden


#line 54 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  
    
#line default
#line hidden


#line 55 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderExample(docComment.Example));

#line default
#line hidden


#line 55 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSeeAlso(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 59 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.SeeAlsoReferences == null || !docComment.SeeAlsoReferences.Any()) { return; }
    
#line default
#line hidden


#line 61 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("See Also"));

#line default
#line hidden


#line 61 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <ul>\r\n");



#line 64 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var seeAlso in docComment.SeeAlsoReferences.OrderBy(sa => sa.ReferencedElementName))
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <li>");



#line 66 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, seeAlso.ReferencedElementName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 67 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </p>\r\n");



#line 70 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExceptionTable(InterfaceDocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 73 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null) { return; }
    
#line default
#line hidden


#line 75 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderExceptionTable(docComment.Exceptions));

#line default
#line hidden


#line 75 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExceptionTable(MethodDocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 79 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null) { return; }
    
#line default
#line hidden


#line 81 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderExceptionTable(docComment.Exceptions));

#line default
#line hidden


#line 81 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExceptionTable(PropertyDocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 85 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null) { return; }
    
#line default
#line hidden


#line 87 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderExceptionTable(docComment.Exceptions));

#line default
#line hidden


#line 87 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderExceptionTable(IList<ExceptionTag> exceptions)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 91 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (exceptions == null || !exceptions.Any()) { return; }
    
    
#line default
#line hidden


#line 94 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Exceptions"));

#line default
#line hidden


#line 94 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Exception</th>\r\n                <th>Description</th>\r\n  " +
"          </tr>\r\n");



#line 101 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var exceptionTag in exceptions)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 104 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, exceptionTag.ExceptionType);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>");



#line 105 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderException(exceptionTag));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                </tr>\r\n");



#line 107 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 110 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamTable(InterfaceBase interfaceModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 113 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (interfaceModel.TypeParameters == null || !interfaceModel.TypeParameters.Any()) { return; }
    
#line default
#line hidden


#line 115 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderTypeParamTable(interfaceModel.TypeParameters, interfaceModel.DocComment == null ? null : interfaceModel.DocComment.TypeParameters));

#line default
#line hidden


#line 115 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                              

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamTable(MethodModel methodModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 119 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (methodModel.TypeParameters == null || !methodModel.TypeParameters.Any()) { return; }
    
#line default
#line hidden


#line 121 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderTypeParamTable(methodModel.TypeParameters, methodModel.DocComment == null ? null : methodModel.DocComment.TypeParameters));

#line default
#line hidden


#line 121 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                     

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamTable(DelegateModel delegateModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 125 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (delegateModel.TypeParameters == null || !delegateModel.TypeParameters.Any()) { return; }
    
#line default
#line hidden


#line 127 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderTypeParamTable(delegateModel.TypeParameters, delegateModel.DocComment == null ? null : delegateModel.DocComment.TypeParameters));

#line default
#line hidden


#line 127 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                           

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderTypeParamTable(IList<TypeParameterModel> typeParams, IList<TypeParameterTag> typeParamComments)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 131 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    var paramToCommentMap = new Dictionary<string, TypeParameterTag>();
    if (typeParamComments != null)
    {
        paramToCommentMap = typeParamComments.ToDictionary(tag => tag.Name, tag => tag);
    }
    
    
#line default
#line hidden


#line 138 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Type Parameters"));

#line default
#line hidden


#line 138 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                          


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Parameter Type</th>\r\n                <th>Description</th" +
">\r\n            </tr>\r\n");



#line 146 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var typeParam in typeParams)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 149 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, typeParam.Name + (!String.IsNullOrWhiteSpace(typeParam.Constraint) ? " : " + typeParam.Constraint : String.Empty));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " </td>\r\n                    <td>\r\n");



#line 151 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (paramToCommentMap.ContainsKey(typeParam.Name))
                        {
                            
#line default
#line hidden


#line 153 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTypeParam(paramToCommentMap[typeParam.Name]));

#line default
#line hidden


#line 153 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                          
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 157 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 160 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParameterTable(MethodModel methodModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 163 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (methodModel.Parameters == null || !methodModel.Parameters.Any()) { return; }
    
#line default
#line hidden


#line 165 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderParamaterTable(methodModel.Parameters, methodModel.DocComment == null ? null : methodModel.DocComment.Parameters));

#line default
#line hidden


#line 165 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                             

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParameterTable(ConstructorModel constructorModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 169 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (constructorModel.Parameters == null || !constructorModel.Parameters.Any()) { return; }
    
#line default
#line hidden


#line 171 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderParamaterTable(constructorModel.Parameters, constructorModel.DocComment == null ? null : constructorModel.DocComment.Parameters));

#line default
#line hidden


#line 171 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                            

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParameterTable(DelegateModel delegateModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 175 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (delegateModel.Parameters == null || !delegateModel.Parameters.Any()) { return; }
    
#line default
#line hidden


#line 177 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderParamaterTable(delegateModel.Parameters, delegateModel.DocComment == null ? null : delegateModel.DocComment.Parameters));

#line default
#line hidden


#line 177 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                   

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderParamaterTable(IList<ParameterModel> parameters, IList<ParameterTag> parameterComments)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 181 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    var paramToCommentMap = new Dictionary<string, ParameterTag>();
    if (parameterComments != null)
    {
        paramToCommentMap = parameterComments.ToDictionary(tag => tag.Name, tag => tag);
    }

    
#line default
#line hidden


#line 188 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Parameters"));

#line default
#line hidden


#line 188 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table3col table-bordered table-hover\">\r\n    " +
"        <tr>\r\n                <th>Type</th>\r\n                <th>Parameter Name<" +
"/th>\r\n                <th>Description</th>\r\n            </tr>\r\n");



#line 196 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var param in parameters)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 199 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, param.TypeName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>");



#line 200 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, param.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 202 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (paramToCommentMap.ContainsKey(param.Name))
                        {
                            
#line default
#line hidden


#line 204 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderParam(paramToCommentMap[param.Name]));

#line default
#line hidden


#line 204 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                  
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 208 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 211 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderConstructorTable(ClassAndStructBase classAndStructBase)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 214 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (classAndStructBase.Constructors == null || !classAndStructBase.Constructors.Any()) { return; }
    
    
#line default
#line hidden


#line 217 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Constructors"));

#line default
#line hidden


#line 217 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                       


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Constructor Name</th>\r\n                <th>Description</" +
"th>\r\n            </tr>\r\n");



#line 225 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var constructor in classAndStructBase.Constructors)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 228 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(constructor));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 230 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (constructor.DocComment != null && constructor.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 232 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(constructor.DocComment.Summary));

#line default
#line hidden


#line 232 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                          
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 236 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 239 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderPropertyTable(InterfaceBase interfaceModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 242 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (interfaceModel.Properties == null || !interfaceModel.Properties.Any()) { return; }
    
    
#line default
#line hidden


#line 245 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Properties"));

#line default
#line hidden


#line 245 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                     


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table3col table-bordered table-hover\">\r\n    " +
"        <tr>\r\n                <th>Type</th>\r\n                <th>Property Name</" +
"th>\r\n                <th>Description</th>\r\n            </tr>\r\n");



#line 254 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var property in interfaceModel.Properties)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 257 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, property.TypeName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>");



#line 258 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(property));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 260 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (property.DocComment != null && property.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 262 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(property.DocComment.Summary));

#line default
#line hidden


#line 262 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                       
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 266 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 269 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderMethodTable(InterfaceBase interfaceModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 272 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (interfaceModel.Methods == null || !interfaceModel.Methods.Any()) { return; }
    
    
#line default
#line hidden


#line 275 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Methods"));

#line default
#line hidden


#line 275 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Method Name</th>\r\n                <th>Description</th>\r\n" +
"            </tr>\r\n");



#line 282 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var method in interfaceModel.Methods)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 285 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(method));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 287 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (method.DocComment != null && method.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 289 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(method.DocComment.Summary));

#line default
#line hidden


#line 289 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                     
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n");



#line 293 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 296 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderReturnValueTable(MethodModel methodModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 299 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    
#line default
#line hidden


#line 300 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderReturnValueTable(methodModel.ReturnType, methodModel.DocComment == null ? null : methodModel.DocComment.Returns));

#line default
#line hidden


#line 300 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                            

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderReturnValueTable(DelegateModel delegateModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 304 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    
#line default
#line hidden


#line 305 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderReturnValueTable(delegateModel.ReturnType, delegateModel.DocComment == null ? null : delegateModel.DocComment.Returns));

#line default
#line hidden


#line 305 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                  

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderReturnValueTable(string returnType, ReturnsTag returnsTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 309 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if ("void".Equals(returnType, StringComparison.Ordinal)) { return; }
    
    
#line default
#line hidden


#line 312 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Returns"));

#line default
#line hidden


#line 312 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Return Type</th>\r\n                <th>Description</th>\r\n" +
"            </tr>  \r\n            <tr>\r\n                <td>");



#line 321 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, returnType);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                <td>\r\n");



#line 323 "..\..\Output\Html\Helpers\PageSection.cshtml"
                     if (returnsTag != null)
                    {
                        
#line default
#line hidden


#line 325 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderReturns(returnsTag));

#line default
#line hidden


#line 325 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                             
                    }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n        </table>\r\n    </p>\r\n");



#line 331 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderInterfaceTable(NamespaceBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 334 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.Interfaces == null || !parent.Interfaces.Any()) { return; }
    
#line default
#line hidden


#line 336 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Interfaces"));

#line default
#line hidden


#line 336 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                     
    
#line default
#line hidden


#line 337 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderInterfaceTable(parent.Interfaces));

#line default
#line hidden


#line 337 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                             

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderInterfaceTable(ClassAndStructBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 341 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.InnerInterfaces == null || !parent.InnerInterfaces.Any()) { return; }
    
#line default
#line hidden


#line 343 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Nested Classes"));

#line default
#line hidden


#line 343 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                         
    
#line default
#line hidden


#line 344 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderInterfaceTable(parent.InnerInterfaces));

#line default
#line hidden


#line 344 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                  

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderInterfaceTable(IList<InterfaceModel> interfaces)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 348 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Name</th>\r\n                <th>Description</th>\r\n       " +
"     </tr>\r\n");



#line 355 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var childInterface in interfaces)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 358 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(childInterface));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 360 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (childInterface.DocComment != null && childInterface.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 362 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(childInterface.DocComment.Summary));

#line default
#line hidden


#line 362 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                             
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 366 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 369 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderClassTable(NamespaceBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 372 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.Classes == null || !parent.Classes.Any()) { return; }
    
#line default
#line hidden


#line 374 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Classes"));

#line default
#line hidden


#line 374 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  
    
#line default
#line hidden


#line 375 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderClassTable(parent.Classes));

#line default
#line hidden


#line 375 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                      

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderClassTable(ClassAndStructBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 379 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.InnerClasses == null || !parent.InnerClasses.Any()) { return; }
    
#line default
#line hidden


#line 381 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Nested Classes"));

#line default
#line hidden


#line 381 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                         
    
#line default
#line hidden


#line 382 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderClassTable(parent.InnerClasses));

#line default
#line hidden


#line 382 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                           

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderClassTable(IList<ClassModel> classes)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 386 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Name</th>\r\n                <th>Description</th>\r\n       " +
"     </tr>\r\n");



#line 393 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var childClass in classes)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 396 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(childClass));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 398 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if(childClass.DocComment != null && childClass.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 400 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(childClass.DocComment.Summary));

#line default
#line hidden


#line 400 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                         
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 404 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 407 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderStructTable(NamespaceBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 410 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.Structs == null || !parent.Structs.Any()) { return; }
    
#line default
#line hidden


#line 412 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Structs"));

#line default
#line hidden


#line 412 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                  
    
#line default
#line hidden


#line 413 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderStructTable(parent.Structs));

#line default
#line hidden


#line 413 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                       

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderStructTable(ClassAndStructBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 417 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.InnerStructs == null || !parent.InnerStructs.Any()) { return; }
    
#line default
#line hidden


#line 419 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Nested Structs"));

#line default
#line hidden


#line 419 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                         
    
#line default
#line hidden


#line 420 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderStructTable(parent.InnerStructs));

#line default
#line hidden


#line 420 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                            

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderStructTable(IList<StructModel> structs)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 424 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Name</th>\r\n                <th>Description</th>\r\n       " +
"     </tr>\r\n");



#line 431 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var childStruct in structs)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 434 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(childStruct));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 436 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (childStruct.DocComment != null && childStruct.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 438 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(childStruct.DocComment.Summary));

#line default
#line hidden


#line 438 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                          
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 442 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 445 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderEnumTable(NamespaceBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 448 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.Enums == null || !parent.Enums.Any()) { return; }
    
#line default
#line hidden


#line 450 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Enums"));

#line default
#line hidden


#line 450 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                
    
#line default
#line hidden


#line 451 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderEnumTable(parent.Enums));

#line default
#line hidden


#line 451 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderEnumTable(ClassAndStructBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 455 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.InnerEnums == null || !parent.InnerEnums.Any()) { return; }
    
#line default
#line hidden


#line 457 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Nested Enums"));

#line default
#line hidden


#line 457 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                       
    
#line default
#line hidden


#line 458 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderEnumTable(parent.InnerEnums));

#line default
#line hidden


#line 458 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                        

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderEnumTable(IList<EnumModel> enums)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 462 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Name</th>\r\n                <th>Description</th>\r\n       " +
"     </tr>\r\n");



#line 469 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var childEnum in enums)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 472 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(childEnum));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 474 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (childEnum.DocComment != null && childEnum.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 476 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(childEnum.DocComment.Summary));

#line default
#line hidden


#line 476 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                        
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 480 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 483 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderDelegateTable(NamespaceBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 486 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.Delegates == null || !parent.Delegates.Any()) { return; }
    
#line default
#line hidden


#line 488 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Delegates"));

#line default
#line hidden


#line 488 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                    
    
#line default
#line hidden


#line 489 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderDelegateTable(parent.Delegates));

#line default
#line hidden


#line 489 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                           

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderDelegateTable(ClassAndStructBase parent)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 493 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (parent.InnerDelegates == null || !parent.InnerDelegates.Any()) { return; }
    
#line default
#line hidden


#line 495 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, RenderSectionTitle("Inner Delegates"));

#line default
#line hidden


#line 495 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                          
    
#line default
#line hidden


#line 496 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderDelegateTable(parent.InnerDelegates));

#line default
#line hidden


#line 496 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderDelegateTable(IList<DelegateModel> delegates)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 500 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Name</th>\r\n                <th>Description</th>\r\n       " +
"     </tr>\r\n");



#line 507 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var childDelegate in delegates)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 510 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, PageHelper.RenderElementLink(childDelegate));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 512 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (childDelegate.DocComment != null && childDelegate.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 514 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTableSummary(childDelegate.DocComment.Summary));

#line default
#line hidden


#line 514 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                            
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 518 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 521 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


        public PageSection()
        {
        }
    }
}
#pragma warning restore 1591
