#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Helpers
{
    
    #line 2 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 4 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    #line 5 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Core.Models.Comments;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Core.Models.Comments.Xml;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Output\Html\Helpers\PageSection.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class PageSection : System.Web.WebPages.HelperPage
    {

public static System.Web.WebPages.HelperResult RenderDeclarationBlock(string declaration)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 11 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"code-block\">\r\n        <pre><code class=\"cs\">");



#line 13 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, declaration);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</code></pre>\r\n    </div>\r\n");



#line 15 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderSectionTitle(string title)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 18 "..\..\Output\Html\Helpers\PageSection.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p><h3>");



#line 19 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</h3></p>\r\n");



#line 20 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSummary(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 23 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.Summary == null) { return; }
    
#line default
#line hidden


#line 25 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Summary"));

#line default
#line hidden


#line 25 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>");



#line 26 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderSummary(docComment.Summary));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</p> \r\n");



#line 27 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderRemarks(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 30 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.Remarks == null) { return; }
    
#line default
#line hidden


#line 32 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Remarks"));

#line default
#line hidden


#line 32 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>");



#line 33 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderRemarks(docComment.Remarks));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 34 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExample(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 37 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.Example == null) { return; }
    
#line default
#line hidden


#line 39 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Example"));

#line default
#line hidden


#line 39 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>");



#line 40 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderExample(docComment.Example));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 41 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderSeeAlso(DocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 44 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null || docComment.SeeAlso == null) { return; }
    
#line default
#line hidden


#line 46 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("See Also"));

#line default
#line hidden


#line 46 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>");



#line 47 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderSeeAlso(docComment.SeeAlso));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 48 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExceptionTable(InterfaceDocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 51 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null) { return; }
    
#line default
#line hidden


#line 53 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderExceptionTable(docComment.Exceptions));

#line default
#line hidden


#line 53 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExceptionTable(MethodDocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 57 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null) { return; }
    
#line default
#line hidden


#line 59 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderExceptionTable(docComment.Exceptions));

#line default
#line hidden


#line 59 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderExceptionTable(PropertyDocComment docComment)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 63 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (docComment == null) { return; }
    
#line default
#line hidden


#line 65 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderExceptionTable(docComment.Exceptions));

#line default
#line hidden


#line 65 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                 

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderExceptionTable(IList<ExceptionTag> exceptions)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 69 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (exceptions == null || !exceptions.Any()) { return; }
    
    
#line default
#line hidden


#line 72 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Exceptions"));

#line default
#line hidden


#line 72 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                      

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Exception</th>\r\n                <th>Description</th>\r\n  " +
"          </tr>\r\n");



#line 79 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var exceptionTag in exceptions)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 82 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, exceptionTag.ExceptionType);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>");



#line 83 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderException(exceptionTag));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                </tr>\r\n");



#line 85 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 88 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamTable(InterfaceBase interfaceModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 91 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (interfaceModel.TypeParameters == null || !interfaceModel.TypeParameters.Any()) { return; }
    
#line default
#line hidden


#line 93 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderTypeParamTable(interfaceModel.TypeParameters, interfaceModel.DocComment == null ? null : interfaceModel.DocComment.TypeParameters));

#line default
#line hidden


#line 93 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                              

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamTable(MethodModel methodModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 97 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (methodModel.TypeParameters == null || !methodModel.TypeParameters.Any()) { return; }
    
#line default
#line hidden


#line 99 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderTypeParamTable(methodModel.TypeParameters, methodModel.DocComment == null ? null : methodModel.DocComment.TypeParameters));

#line default
#line hidden


#line 99 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                     

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderTypeParamTable(DelegateModel delegateModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 103 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (delegateModel.TypeParameters == null || !delegateModel.TypeParameters.Any()) { return; }
    
#line default
#line hidden


#line 105 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderTypeParamTable(delegateModel.TypeParameters, delegateModel.DocComment == null ? null : delegateModel.DocComment.TypeParameters));

#line default
#line hidden


#line 105 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                           

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderTypeParamTable(IList<TypeParameterModel> typeParams, IList<TypeParameterTag> typeParamComments)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 109 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    var paramToCommentMap = new Dictionary<string, TypeParameterTag>();
    if (typeParamComments != null)
    {
        paramToCommentMap = typeParamComments.ToDictionary(tag => tag.Name, tag => tag);
    }
    
    
#line default
#line hidden


#line 116 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Type Parameters"));

#line default
#line hidden


#line 116 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                           


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n");



#line 120 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var typeParam in typeParams)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 123 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, typeParam.Name + (!String.IsNullOrWhiteSpace(typeParam.Constraint) ? " : " + typeParam.Constraint : String.Empty));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " </td>\r\n                    <td>\r\n");



#line 125 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (paramToCommentMap.ContainsKey(typeParam.Name))
                        {
                            
#line default
#line hidden


#line 127 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderTypeParam(paramToCommentMap[typeParam.Name]));

#line default
#line hidden


#line 127 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                          
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n");



#line 131 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 134 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParameterTable(MethodModel methodModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 137 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (methodModel.Parameters == null || !methodModel.Parameters.Any()) { return; }
    
#line default
#line hidden


#line 139 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderParamaterTable(methodModel.Parameters, methodModel.DocComment == null ? null : methodModel.DocComment.Parameters));

#line default
#line hidden


#line 139 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                             

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParameterTable(ConstructorModel constructorModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 143 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (constructorModel.Parameters == null || !constructorModel.Parameters.Any()) { return; }
    
#line default
#line hidden


#line 145 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderParamaterTable(constructorModel.Parameters, constructorModel.DocComment == null ? null : constructorModel.DocComment.Parameters));

#line default
#line hidden


#line 145 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                            

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderParameterTable(DelegateModel delegateModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 149 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (delegateModel.Parameters == null || !delegateModel.Parameters.Any()) { return; }
    
#line default
#line hidden


#line 151 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderParamaterTable(delegateModel.Parameters, delegateModel.DocComment == null ? null : delegateModel.DocComment.Parameters));

#line default
#line hidden


#line 151 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                   

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderParamaterTable(IList<ParameterModel> parameters, IList<ParameterTag> parameterComments)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 155 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    var paramToCommentMap = new Dictionary<string, ParameterTag>();
    if (parameterComments != null)
    {
        paramToCommentMap = parameterComments.ToDictionary(tag => tag.Name, tag => tag);
    }

    
#line default
#line hidden


#line 162 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Parameters"));

#line default
#line hidden


#line 162 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                      

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table3col table-bordered table-hover\">\r\n");



#line 165 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var param in parameters)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 168 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, param.TypeName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>");



#line 169 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, param.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 171 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (paramToCommentMap.ContainsKey(param.Name))
                        {
                            
#line default
#line hidden


#line 173 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderParam(paramToCommentMap[param.Name]));

#line default
#line hidden


#line 173 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                  
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </td>\r\n                </tr>\r\n");



#line 177 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 180 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderConstructorTable(ClassAndStructBase classAndStructBase)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 183 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (classAndStructBase.Constructors == null || !classAndStructBase.Constructors.Any()) { return; }
    
    
#line default
#line hidden


#line 186 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Constructors"));

#line default
#line hidden


#line 186 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                        


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Constructor Name</th>\r\n                <th>Description</" +
"th>\r\n            </tr>\r\n");



#line 194 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var constructor in classAndStructBase.Constructors)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 197 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, constructor.DisplayName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 199 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (constructor.DocComment != null && constructor.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 201 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderSummary(constructor.DocComment.Summary));

#line default
#line hidden


#line 201 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                     
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n");



#line 205 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 208 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderPropertyTable(InterfaceBase interfaceModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 211 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (interfaceModel.Properties == null || !interfaceModel.Properties.Any()) { return; }
    
    
#line default
#line hidden


#line 214 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Properties"));

#line default
#line hidden


#line 214 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                      


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Property Name</th>\r\n                <th>Description</th>" +
"\r\n            </tr>\r\n");



#line 222 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var property in interfaceModel.Properties)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 225 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, property.DisplayName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 227 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (property.DocComment != null && property.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 229 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderSummary(property.DocComment.Summary));

#line default
#line hidden


#line 229 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                  
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n");



#line 233 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 236 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderMethodTable(InterfaceBase interfaceModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 239 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if (interfaceModel.Methods == null || !interfaceModel.Methods.Any()) { return; }
    
    
#line default
#line hidden


#line 242 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Methods"));

#line default
#line hidden


#line 242 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Method Name</th>\r\n                <th>Description</th>\r\n" +
"            </tr>\r\n");



#line 249 "..\..\Output\Html\Helpers\PageSection.cshtml"
             foreach (var method in interfaceModel.Methods)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td>");



#line 252 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, method.DisplayName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td>\r\n");



#line 254 "..\..\Output\Html\Helpers\PageSection.cshtml"
                         if (method.DocComment != null && method.DocComment.Summary != null)
                        {
                            
#line default
#line hidden


#line 256 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderSummary(method.DocComment.Summary));

#line default
#line hidden


#line 256 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n");



#line 260 "..\..\Output\Html\Helpers\PageSection.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </p>\r\n");



#line 263 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderReturnValueTable(MethodModel methodModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 266 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    
#line default
#line hidden


#line 267 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderReturnValueTable(methodModel.ReturnType, methodModel.DocComment == null ? null : methodModel.DocComment.Returns));

#line default
#line hidden


#line 267 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                            

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderReturnValueTable(DelegateModel delegateModel)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 271 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    
#line default
#line hidden


#line 272 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderReturnValueTable(delegateModel.ReturnType, delegateModel.DocComment == null ? null : delegateModel.DocComment.Returns));

#line default
#line hidden


#line 272 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                                                                                                  

#line default
#line hidden

});

}


internal static System.Web.WebPages.HelperResult _RenderReturnValueTable(string returnType, ReturnsTag returnsTag)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 276 "..\..\Output\Html\Helpers\PageSection.cshtml"
 
    if ("void".Equals(returnType, StringComparison.Ordinal)) { return; }
    
    
#line default
#line hidden


#line 279 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, _RenderSectionTitle("Returns"));

#line default
#line hidden


#line 279 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                   
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Return Type</th>\r\n                <th>Description</th>\r\n" +
"            </tr>  \r\n            <tr>\r\n                <td>");



#line 288 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, returnType);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                <td>\r\n");



#line 290 "..\..\Output\Html\Helpers\PageSection.cshtml"
                     if (returnsTag != null)
                    {
                        
#line default
#line hidden


#line 292 "..\..\Output\Html\Helpers\PageSection.cshtml"
WriteTo(@__razor_helper_writer, CommentTag.RenderReturns(returnsTag));

#line default
#line hidden


#line 292 "..\..\Output\Html\Helpers\PageSection.cshtml"
                                                             
                    }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                </td>\r\n            </tr>\r\n        </table>\r\n    </p>\r\n");



#line 298 "..\..\Output\Html\Helpers\PageSection.cshtml"

#line default
#line hidden

});

}


        public PageSection()
        {
        }
    }
}
#pragma warning restore 1591
