#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Output\Html\Views\ClassDetail.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Output\Html\Views\ClassDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\ClassDetail.cshtml"
    using DocNet.Core.Output.Html.Helpers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\ClassDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Views\ClassDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ClassDetail : BodyTemplate<ClassModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n<!--Name-->\r\n<p>\r\n    <h3>Class</h3>\r\n    <h1>");


            
            #line 12 "..\..\Output\Html\Views\ClassDetail.cshtml"
   Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <h3>Namespace: ");


            
            #line 13 "..\..\Output\Html\Views\ClassDetail.cshtml"
              Write(Model.FullNameQualifier);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n</p>\r\n\r\n");


            
            #line 16 "..\..\Output\Html\Views\ClassDetail.cshtml"
Write(PageSection.RenderDeclarationBlock(GetDeclaration.OfClass(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 18 "..\..\Output\Html\Views\ClassDetail.cshtml"
Write(PageSection.RenderSummary(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 20 "..\..\Output\Html\Views\ClassDetail.cshtml"
 if (Model.Constructors.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Constructors-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Constructors</h3>\r\n        <table class=\"table table-bordere" +
"d table-hover\">\r\n            <tr>\r\n                <td><b>Constructor Name</b></" +
"td>\r\n                <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 29 "..\..\Output\Html\Views\ClassDetail.cshtml"
             foreach (ConstructorModel c in Model.Constructors){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 31 "..\..\Output\Html\Views\ClassDetail.cshtml"
                   Write(c.Identifier);

            
            #line default
            #line hidden

            
            #line 31 "..\..\Output\Html\Views\ClassDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 32 "..\..\Output\Html\Views\ClassDetail.cshtml"
                         if (c.DocComment != null){
                            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Output\Html\Views\ClassDetail.cshtml"
                       Write(CommentTag.RenderSummary(c.DocComment.Summary));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Output\Html\Views\ClassDetail.cshtml"
                                                                           
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 36 "..\..\Output\Html\Views\ClassDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 39 "..\..\Output\Html\Views\ClassDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 41 "..\..\Output\Html\Views\ClassDetail.cshtml"
 if (Model.Properties.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Properties-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Properties</h3>\r\n        <table class=\"table table-bordered " +
"table-hover\">\r\n            <tr>\r\n                <td><b>Property Name</b></td>\r\n" +
"                <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 50 "..\..\Output\Html\Views\ClassDetail.cshtml"
             foreach (PropertyModel p in Model.Properties){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 52 "..\..\Output\Html\Views\ClassDetail.cshtml"
                   Write(p.Identifier);

            
            #line default
            #line hidden

            
            #line 52 "..\..\Output\Html\Views\ClassDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 53 "..\..\Output\Html\Views\ClassDetail.cshtml"
                         if (p.DocComment != null){
                            
            
            #line default
            #line hidden
            
            #line 54 "..\..\Output\Html\Views\ClassDetail.cshtml"
                       Write(CommentTag.RenderSummary(p.DocComment.Summary));

            
            #line default
            #line hidden
            
            #line 54 "..\..\Output\Html\Views\ClassDetail.cshtml"
                                                                           
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 57 "..\..\Output\Html\Views\ClassDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 60 "..\..\Output\Html\Views\ClassDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 62 "..\..\Output\Html\Views\ClassDetail.cshtml"
 if (Model.Methods.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Methods-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Methods</h3>\r\n        <table class=\"table table-bordered tab" +
"le-hover\">\r\n            <tr>\r\n                <td><b>Method Name</b></td>\r\n     " +
"           <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 71 "..\..\Output\Html\Views\ClassDetail.cshtml"
             foreach (MethodModel m in Model.Methods){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 73 "..\..\Output\Html\Views\ClassDetail.cshtml"
                   Write(m.Identifier);

            
            #line default
            #line hidden

            
            #line 73 "..\..\Output\Html\Views\ClassDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 74 "..\..\Output\Html\Views\ClassDetail.cshtml"
                         if (m.DocComment != null){
                            
            
            #line default
            #line hidden
            
            #line 75 "..\..\Output\Html\Views\ClassDetail.cshtml"
                       Write(CommentTag.RenderSummary(m.DocComment.Summary));

            
            #line default
            #line hidden
            
            #line 75 "..\..\Output\Html\Views\ClassDetail.cshtml"
                                                                           
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 78 "..\..\Output\Html\Views\ClassDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 81 "..\..\Output\Html\Views\ClassDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--Exceptions-->\r\n\r\n");


            
            #line 85 "..\..\Output\Html\Views\ClassDetail.cshtml"
Write(PageSection.RenderRemarks(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 87 "..\..\Output\Html\Views\ClassDetail.cshtml"
Write(PageSection.RenderExample(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 89 "..\..\Output\Html\Views\ClassDetail.cshtml"
Write(PageSection.RenderSeeAlso(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
