#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Output\Html\Views\DelegateDetail.cshtml"
    using DocNet.Core.Models.Comments.Xml;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Output\Html\Views\DelegateDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\DelegateDetail.cshtml"
    using DocNet.Core.Output.Html.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\DelegateDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Views\DelegateDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class DelegateDetail : BodyTemplate<DelegateModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n<p><h1>Delegate: ");


            
            #line 9 "..\..\Output\Html\Views\DelegateDetail.cshtml"
            Write(Model.FullDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</h1></p>\r\n\r\n");


            
            #line 11 "..\..\Output\Html\Views\DelegateDetail.cshtml"
Write(PageSection.RenderDeclarationBlock(GetDeclaration.OfDelegate(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 13 "..\..\Output\Html\Views\DelegateDetail.cshtml"
 if (Model.DocComment != null){

            
            #line default
            #line hidden
WriteLiteral("    <!--Summary-->\r\n");




            
            #line 15 "..\..\Output\Html\Views\DelegateDetail.cshtml"
WriteLiteral("    <p>");

            
            #line default
            #line hidden
            
            #line 15 "..\..\Output\Html\Views\DelegateDetail.cshtml"
          CommentTag.RenderSummary(Model.DocComment.Summary); 
            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 16 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Type Parameters-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Type Parameters</h3>\r\n        <table class=\"table table-bord" +
"ered table-hover\">\r\n");


            
            #line 21 "..\..\Output\Html\Views\DelegateDetail.cshtml"
             foreach (TypeParameterTag t in Model.DocComment.TypeParameters){

            
            #line default
            #line hidden

            
            #line 22 "..\..\Output\Html\Views\DelegateDetail.cshtml"
WriteLiteral("                <tr>");

            
            #line default
            #line hidden
            
            #line 22 "..\..\Output\Html\Views\DelegateDetail.cshtml"
                       CommentTag.RenderTypeParam(t); 
            
            #line default
            #line hidden
WriteLiteral("</tr>\r\n");


            
            #line 23 "..\..\Output\Html\Views\DelegateDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 26 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Returns-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Returns</h3>\r\n");


            
            #line 30 "..\..\Output\Html\Views\DelegateDetail.cshtml"
           CommentTag.RenderReturns(Model.DocComment.Returns); 

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 32 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Parameters-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Parameters</h3>\r\n        <table class=\"table table-bordered " +
"table-hover\">\r\n");


            
            #line 37 "..\..\Output\Html\Views\DelegateDetail.cshtml"
             foreach (ParameterTag p in Model.DocComment.Parameters){

            
            #line default
            #line hidden

            
            #line 38 "..\..\Output\Html\Views\DelegateDetail.cshtml"
WriteLiteral("                <tr><td>");

            
            #line default
            #line hidden
            
            #line 38 "..\..\Output\Html\Views\DelegateDetail.cshtml"
                           CommentTag.RenderParam(p); 
            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 39 "..\..\Output\Html\Views\DelegateDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 42 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Exceptions-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Exceptions</h3>\r\n        <table class=\"table table-bordered " +
"table-hover\">\r\n");


            
            #line 47 "..\..\Output\Html\Views\DelegateDetail.cshtml"
             foreach (ExceptionTag e in Model.DocComment.Exceptions){

            
            #line default
            #line hidden

            
            #line 48 "..\..\Output\Html\Views\DelegateDetail.cshtml"
WriteLiteral("                <tr><td>");

            
            #line default
            #line hidden
            
            #line 48 "..\..\Output\Html\Views\DelegateDetail.cshtml"
                           CommentTag.RenderException(e); 
            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 49 "..\..\Output\Html\Views\DelegateDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 52 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Remarks-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Remarks</h3>\r\n");


            
            #line 56 "..\..\Output\Html\Views\DelegateDetail.cshtml"
           CommentTag.RenderRemarks(Model.DocComment.Remarks); 

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 58 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Example-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Example</h3>\r\n");


            
            #line 62 "..\..\Output\Html\Views\DelegateDetail.cshtml"
           CommentTag.RenderExample(Model.DocComment.Example); 

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 64 "..\..\Output\Html\Views\DelegateDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--See Also-->\r\n");



WriteLiteral("    <p>\r\n        <h3>See Also</h3>\r\n");


            
            #line 68 "..\..\Output\Html\Views\DelegateDetail.cshtml"
           CommentTag.RenderSeeAlso(Model.DocComment.SeeAlso); 

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 70 "..\..\Output\Html\Views\DelegateDetail.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
