#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
    using DocNet.Core.Output.Html.Helpers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class InterfaceDetail : BodyTemplate<InterfaceModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n<p>Interface: ");


            
            #line 9 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
         Write(Model.FullDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");


            
            #line 11 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
Write(PageSection.RenderDeclarationBlock(GetDeclaration.OfInterface(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 13 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
 if (Model.DocComment != null){

            
            #line default
            #line hidden
WriteLiteral("    <!--Summary-->\r\n");




            
            #line 15 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
WriteLiteral("    <p>");

            
            #line default
            #line hidden
            
            #line 15 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
          CommentTag.RenderSummary(Model.DocComment.Summary); 
            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 16 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 18 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
 if (Model.Methods.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Methods-->\r\n");



WriteLiteral("    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n");


            
            #line 22 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
             foreach (MethodModel m in Model.Methods){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 24 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
                   Write(m.Identifier);

            
            #line default
            #line hidden

            
            #line 24 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 25 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
                         if (m.DocComment != null){
                            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
                       Write(m.DocComment.Summary);

            
            #line default
            #line hidden
            
            #line 26 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
                                                 
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 29 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 32 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 34 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
 if (Model.DocComment != null){

            
            #line default
            #line hidden
WriteLiteral("    <!--Remarks-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Remarks</h3>\r\n");


            
            #line 38 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
           CommentTag.RenderRemarks(Model.DocComment.Remarks); 

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 40 "..\..\Output\Html\Views\InterfaceDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--See Also-->\r\n");



WriteLiteral("    <p>\r\n        <h3>See Also</h3>\r\n");


            
            #line 44 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
           CommentTag.RenderSeeAlso(Model.DocComment.SeeAlso); 

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 46 "..\..\Output\Html\Views\InterfaceDetail.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
