#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.18408
=======
//     Runtime Version:4.0.30319.34209
>>>>>>> 958141ec6b3aff360e03e5c5d5bd5a43366e0889
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Output\Html\Views\Layout.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\Layout.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Layout : BodyTemplate<InterfaceModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n");


            
            #line 6 "..\..\Output\Html\Views\Layout.cshtml"
  
	var itemPath = 0;
    var projectName = 0;
	var hierarchy = new []{0};
    var parent = 0;
	var view = 0;
	var count = 0;
	var inTree = "";
	var glyph = "right";
    var childOfItem = 0;


            
            #line default
            #line hidden
WriteLiteral(@"
<?xml version=""1.0"" encoding=""utf-8"" ?>

<html>
<head>
    <meta charset=""utf-8"">
    <link href=""css/bootstrap.min.css"" rel=""stylesheet"">
    <link href=""css/bootstrap-theme.min.css"" rel=""stylesheet"">
    <link href=""css/custom.css"" rel=""stylesheet"">
    <script src=""js/jquery-1.9.1.min.js""></script>
    <script src=""js/bootstrap.js""></script>
    <script src=""js/collapse.js""></script>
    <script src=""js/custom.js""></script>
    <title>");


            
            #line 30 "..\..\Output\Html\Views\Layout.cshtml"
       Write(projectName);

            
            #line default
            #line hidden
WriteLiteral(" Documentation - ");


            
            #line 30 "..\..\Output\Html\Views\Layout.cshtml"
                                      Write(view);

            
            #line default
            #line hidden
WriteLiteral(" by DocNet</title>\r\n</head>\r\n\r\n<body>\r\n    <div class=\"container-fluid main\">\r\n  " +
"      <div class=\"page-header row\">\r\n            <div class=\"col-md-2\"><h1>DocNe" +
"t</h1></div>\r\n            <div class=\"col-md-10\">\r\n                <h2>");


            
            #line 38 "..\..\Output\Html\Views\Layout.cshtml"
                Write(view);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n            </div>\r\n        </div>\r\n        <div class=\"row main\">\r\n      " +
"      <div class=\"col-md-2 sidebar\">\r\n                <h2>Sidebar</h2>\r\n        " +
"        <div id=\"over\"><ol>\r\n");


            
            #line 45 "..\..\Output\Html\Views\Layout.cshtml"
                     foreach (int item in hierarchy){
						if( item == parent){
							if(view == childOfItem){
								inTree = " in";
								glyph = "down";
							}
                    

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t            <div class=\"expand link\" onclick=\"hide(this, ");


            
            #line 53 "..\..\Output\Html\Views\Layout.cshtml"
                                                          Write(count);

            
            #line default
            #line hidden
WriteLiteral(")\"><span class=\"glyphicon glyphicon-menu-");


            
            #line 53 "..\..\Output\Html\Views\Layout.cshtml"
                                                                                                           Write(glyph);

            
            #line default
            #line hidden
WriteLiteral("\" aria-hidden=\"true\"></span></div><a href=\"");


            
            #line 53 "..\..\Output\Html\Views\Layout.cshtml"
                                                                                                                                                              Write(itemPath);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 53 "..\..\Output\Html\Views\Layout.cshtml"
                                                                                                                                                                           Write(item);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t            <ol class=\"collapse");


            
            #line 54 "..\..\Output\Html\Views\Layout.cshtml"
                               Write(inTree);

            
            #line default
            #line hidden
WriteLiteral("\" id=\"collapse");


            
            #line 54 "..\..\Output\Html\Views\Layout.cshtml"
                                                      Write(count);

            
            #line default
            #line hidden
WriteLiteral("\"></ol></li>\r\n");


            
            #line 55 "..\..\Output\Html\Views\Layout.cshtml"
							count = count + 1;
						}
						else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<li><span class=\"expand\"></span><a href=\"");


            
            #line 58 "..\..\Output\Html\Views\Layout.cshtml"
                                            Write(itemPath);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 58 "..\..\Output\Html\Views\Layout.cshtml"
                                                         Write(item);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 59 "..\..\Output\Html\Views\Layout.cshtml"
						}
					}

            
            #line default
            #line hidden
WriteLiteral("                </ol></div>\r\n            </div>\r\n            <div class=\"col-md-1" +
"0 content\">\r\n                ");


            
            #line 64 "..\..\Output\Html\Views\Layout.cshtml"
            Write(view);

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>
        </div>
    </div>
    <footer class=""footer"">
        <div class=""container"">
            <p class=""text-muted"">DocNet was created by Stephen Bos, Scott Byrne, Chris Carr, and Keith Rollans.</p>
        </div>
    </footer>
</body>

</html>");


        }
    }
}
#pragma warning restore 1591
