#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class MethodDetail : BaseTemplate<MethodModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Output\Html\Views\MethodDetail.cshtml"
WriteLiteral("\r\n<p><h1>Method: dualAdd</h1></p>\r\n<!--Summary\r\n    Type Parameters\r\n    Returns\r" +
"\n    Parameters\r\n    Exceptions\r\n    Remarks\r\n    Example\r\n    See Also-->\r\n\r\n<!" +
"--Summary-->\r\n<p>");

            
            #line default
            #line hidden
            
            #line 18 "..\..\Output\Html\Views\MethodDetail.cshtml"
     CommentTag.RenderSummary(Model.DocComment.Summary);
            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n<!--Type Parameters-->\r\n<p>\r\n    <h3>Type Parameters</h3>\r\n    <table cel" +
"lpadding=\"10\">\r\n        <tr>\r\n            <td><i>item1</i></td>\r\n            <td" +
">Type: T1</td>\r\n            <td>The object to be added to the first list</td>\r\n " +
"       </tr>\r\n        <tr>\r\n            <td><i>item2</i></td>\r\n            <td>T" +
"ype: T2</td>\r\n            <td>The object to be added to the second list</td>\r\n  " +
"      </tr>\r\n    </table>\r\n</p>\r\n\r\n<!--Returns-->\r\n<p>\r\n    <h3>Returns</h3>\r\n  " +
"  <table cellpadding=\"10\">\r\n        <tr>\r\n            <td>Type: bool</td>\r\n     " +
"       <td>True if both adds succeeded, false otherwise</td>\r\n        </tr>\r\n   " +
" </table>\r\n</p>\r\n\r\n<!--Parameters-->\r\n<p>\r\n    <h3>Parameters</h3>\r\n    <table c" +
"ellpadding=\"10\">\r\n        <tr>\r\n            <td><i>MaxSize1</i></td>\r\n          " +
"  <td>Type: int</td>\r\n            <td>The maximum size of the first list (&lt;0 " +
"means infinite list)</td>\r\n        </tr>\r\n        <tr>\r\n            <td><i>MaxSi" +
"ze2</i></td>\r\n            <td>Type: int</td>\r\n            <td>The maximum size o" +
"f the second list (&lt;0 means infinite list)</td>\r\n        </tr>\r\n    </table>\r" +
"\n</p>\r\n\r\n<!--Exceptions-->\r\n<p>\r\n    <h3>Exceptions</h3>\r\n    <table cellpadding" +
"=\"10\">\r\n        <tr>\r\n            <td>NullPointerException</td>\r\n            <td" +
">One of the item\'s is null</td>\r\n        </tr>\r\n        <tr>\r\n            <td>Bu" +
"llshitException</td>\r\n            <td>Exists solely because I want 2 items under" +
" every category</td>\r\n        </tr>\r\n    </table>\r\n</p>\r\n\r\n<!--Remarks-->\r\n<p>\r\n" +
"    <h3>Remarks</h3>\r\n    This is entirely unremarkable.\r\n</p>\r\n\r\n<!--Example-->" +
"\r\n<p>\r\n    <h3>Example</h3>\r\n    The following snippet demonstrates usage of the" +
" method.\r\n    <br /><br />\r\n    DualList&lt;int, double&gt; dl = new DualList();" +
"<br />\r\n    dl.dualAdd(1,5.6,7,7);\r\n</p>\r\n\r\n<!--See Also-->\r\n<p>\r\n    <h3>See Al" +
"so</h3><br />\r\n    <b>Reference</b><br />\r\n    This page<br />\r\n    This other p" +
"age\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
