#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Core.Models.Comments.Xml;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Core.Output.Html.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Views\MethodDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class MethodDetail : BodyTemplate<MethodModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n<!--Name-->\r\n<p>\r\n    <h3>Method</h3>\r\n    <h1>");


            
            #line 12 "..\..\Output\Html\Views\MethodDetail.cshtml"
   Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <h3>Namespace: ");


            
            #line 13 "..\..\Output\Html\Views\MethodDetail.cshtml"
              Write(Model.FullNameQualifier);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n</p>\r\n\r\n");


            
            #line 16 "..\..\Output\Html\Views\MethodDetail.cshtml"
Write(PageSection.RenderDeclarationBlock(GetDeclaration.OfMethod(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 18 "..\..\Output\Html\Views\MethodDetail.cshtml"
Write(PageSection.RenderSummary(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 20 "..\..\Output\Html\Views\MethodDetail.cshtml"
Write(PageSection.RenderTypeParamTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 22 "..\..\Output\Html\Views\MethodDetail.cshtml"
 if (Model.DocComment != null)
{


    if (Model.DocComment.Returns != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <!--Returns-->\r\n");



WriteLiteral("        <p>\r\n            <h3>Returns</h3>\r\n            ");


            
            #line 31 "..\..\Output\Html\Views\MethodDetail.cshtml"
       Write(CommentTag.RenderReturns(Model.DocComment.Returns));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n");


            
            #line 33 "..\..\Output\Html\Views\MethodDetail.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <!--Parameters-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Parameters</h3>\r\n        <table class=\"table table-bordered " +
"table-hover\">\r\n");


            
            #line 38 "..\..\Output\Html\Views\MethodDetail.cshtml"
             foreach (ParameterTag p in Model.DocComment.Parameters)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr><td>");


            
            #line 40 "..\..\Output\Html\Views\MethodDetail.cshtml"
                   Write(CommentTag.RenderParam(p));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 41 "..\..\Output\Html\Views\MethodDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 44 "..\..\Output\Html\Views\MethodDetail.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <!--Exceptions-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Exceptions</h3>\r\n        <table class=\"table table-bordered " +
"table-hover\">\r\n");


            
            #line 49 "..\..\Output\Html\Views\MethodDetail.cshtml"
             foreach (ExceptionTag e in Model.DocComment.Exceptions)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr><td>");


            
            #line 51 "..\..\Output\Html\Views\MethodDetail.cshtml"
                   Write(CommentTag.RenderException(e));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 52 "..\..\Output\Html\Views\MethodDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 55 "..\..\Output\Html\Views\MethodDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 57 "..\..\Output\Html\Views\MethodDetail.cshtml"
Write(PageSection.RenderRemarks(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 59 "..\..\Output\Html\Views\MethodDetail.cshtml"
Write(PageSection.RenderExample(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 61 "..\..\Output\Html\Views\MethodDetail.cshtml"
Write(PageSection.RenderSeeAlso(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
