#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Core.Output.Html;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class NamespaceDetail : BodyTemplate<NamespaceBase>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n");


            
            #line 9 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderElementTitle(Model, "Namespace"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 11 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
 if(Model.ChildNamespaces != null && Model.ChildNamespaces.Any())
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderSectionTitle("Namespaces"));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                                                 

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        <table class=\"table table-bordered table-hover\">\r\n            <t" +
"r>\r\n                <th>Name</th>\r\n            </tr>\r\n");


            
            #line 19 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
             foreach(var childNamespace in Model.ChildNamespaces)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 22 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                   Write(PageHelper.RenderElementLink(childNamespace));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 24 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table> \r\n    </p>\r\n");


            
            #line 27 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 29 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderInterfaceTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 31 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderClassTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 33 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderStructTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 35 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderEnumTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 37 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
Write(PageSection.RenderDelegateTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
