#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class NamespaceDetail : BodyTemplate<NamespaceBase>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n<!--Name-->\r\n<p><h1>");


            
            #line 9 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
  Write(Model.FullDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</h1></p>\r\n\r\n");


            
            #line 11 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
 if (Model.Classes.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Classes-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Classes</h3>\r\n        <table class=\"table table-bordered tab" +
"le-hover\">\r\n            <tr>\r\n                <td><b>Class Name</b></td>\r\n      " +
"          <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 20 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
             foreach (ClassModel c in Model.Classes){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 22 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                   Write(c.Identifier);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 23 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                     if (c.DocComment != null){

            
            #line default
            #line hidden
WriteLiteral("                        <td>");


            
            #line 24 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                       Write(CommentTag.RenderSummary(c.DocComment.Summary));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 25 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                    }else{

            
            #line default
            #line hidden
WriteLiteral("                        <td></td>\r\n");


            
            #line 27 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");


            
            #line 29 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 32 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 34 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
 if (Model.Structs.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Structures-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Structures</h3>\r\n        <table class=\"table table-bordered " +
"table-hover\">\r\n            <tr>\r\n                <td><b>Structure Name</b></td>\r" +
"\n                <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 43 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
             foreach (StructModel s in Model.Structs){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 45 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                   Write(s.Identifier);

            
            #line default
            #line hidden

            
            #line 45 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 46 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                         if (s.DocComment != null){
                            CommentTag.RenderSummary(s.DocComment.Summary);
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 50 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 53 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 55 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
 if (Model.Delegates.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Delegates-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Delegates</h3>\r\n        <table class=\"table table-bordered t" +
"able-hover\">\r\n            <tr>\r\n                <td><b>Delegate Name</b></td>\r\n " +
"               <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 64 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
             foreach (DelegateModel d in Model.Delegates){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 66 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                   Write(d.Identifier);

            
            #line default
            #line hidden

            
            #line 66 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 67 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                         if (d.DocComment != null){
                            CommentTag.RenderSummary(d.DocComment.Summary);
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 71 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 74 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 76 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
 if (Model.Enums.Any()){

            
            #line default
            #line hidden
WriteLiteral("    <!--Enumerations-->\r\n");



WriteLiteral("    <p>\r\n        <h3>Enumerations</h3>\r\n        <table class=\"table table-bordere" +
"d table-hover\">\r\n            <tr>\r\n                <td><b>Enum Name</b></td>\r\n  " +
"              <td><b>Description</b></td>\r\n            </tr>\r\n");


            
            #line 85 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
             foreach (EnumModel e in Model.Enums){

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 87 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                   Write(e.Identifier);

            
            #line default
            #line hidden

            
            #line 87 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                                     WriteLiteral("</td>\r\n                    <td>");

            
            #line default
            #line hidden
            
            #line 88 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
                         if (e.DocComment != null){
                            CommentTag.RenderSummary(e.DocComment.Summary);
                        }
            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 92 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </p>\r\n");


            
            #line 95 "..\..\Output\Html\Views\NamespaceDetail.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
