#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Output\Html\Views\Page.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\Page.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Page : PageTemplate
    {
#line hidden
#line hidden
public System.Web.WebPages.HelperResult RenderBody()
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 8 "..\..\Output\Html\Views\Page.cshtml"
 
    Body.Execute();

#line default
#line hidden

});

}


        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n<?xml version=\"1.0\" encoding=\"utf-8\" ?>\r\n\r\n<html>\r\n");


            
            #line 15 "..\..\Output\Html\Views\Page.cshtml"
Write(PageHelper.RenderHead(CssFiles, ScriptFiles));

            
            #line default
            #line hidden
WriteLiteral(@"
<body class=""primary"">
    <div class=""flex-body"">
        <div class=""page-head primary"">
            <div><h1><span id=""head1"">Doc</span><span id=""head2"">Net</span></h1></div>
        </div>
        <div class=""main"">
            <div class=""sidebar primary"">
                <div id=""side-well"" class=""normal"">
                    <div id=""over"">
                        <h2>Hierarchy</h2>
                        ");


            
            #line 26 "..\..\Output\Html\Views\Page.cshtml"
                   Write(PageHelper.RenderSidebar(GlobalNamespace, Body.Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div class=\"content normal\">\r\n                ");


            
            #line 31 "..\..\Output\Html\Views\Page.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>
        </div>
        <footer class=""footer"">
            <div class=""container"">
                <p class=""text-muted"">DocNet was created by Stephen Bos, Scott Byrne, Chris Carr, and Keith Rollans.</p>
            </div>
        </footer>
    </div>
</body>

</html>
");


        }
    }
}
#pragma warning restore 1591
