#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Output\Html\Views\Page.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Page : PageTemplate
    {
#line hidden
#line hidden
public System.Web.WebPages.HelperResult RenderBody()
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Output\Html\Views\Page.cshtml"
 
    Body.Execute();

#line default
#line hidden

});

}


        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n<h1>Title</h1>\r\n");


            
            #line 12 "..\..\Output\Html\Views\Page.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
