#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Output\Html\Views\PropertyDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\PropertyDetail.cshtml"
    using DocNet.Core.Output.Html.Helpers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\PropertyDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\PropertyDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PropertyDetail : BodyTemplate<PropertyModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n");


            
            #line 8 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderElementTitle(Model, "Property"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!--Type-->\r\n<span><b>Type:</b> ");


            
            #line 11 "..\..\Output\Html\Views\PropertyDetail.cshtml"
              Write(Model.TypeName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n");


            
            #line 13 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderDeclarationBlock(GetDeclaration.OfProperty(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 15 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderSummary(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 17 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderExceptionTable(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 19 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderRemarks(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 21 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderExample(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 23 "..\..\Output\Html\Views\PropertyDetail.cshtml"
Write(PageSection.RenderSeeAlso(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
