#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocNet.Razor.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Output\Html\Views\StructDetail.cshtml"
    using DocNet.Core.Models.CSharp;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Output\Html\Views\StructDetail.cshtml"
    using DocNet.Core.Output.Html.Helpers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Output\Html\Views\StructDetail.cshtml"
    using DocNet.Core.Output.Html.Views;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Output\Html\Views\StructDetail.cshtml"
    using DocNet.Razor.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class StructDetail : BodyTemplate<StructModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n");


            
            #line 8 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderElementTitle(Model, "Struct"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 10 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderDeclarationBlock(GetDeclaration.OfStruct(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 12 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderSummary(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 14 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderTypeParamTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 16 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderExceptionTable(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 18 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderConstructorTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 20 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderPropertyTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 22 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderMethodTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 24 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderInterfaceTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 26 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderClassTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 28 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderStructTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 30 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderEnumTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 32 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderDelegateTable(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 34 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderRemarks(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 36 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderExample(Model.DocComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 38 "..\..\Output\Html\Views\StructDetail.cshtml"
Write(PageSection.RenderSeeAlso(Model.DocComment));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
